
import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "./StoreProvider";
import { LanguageProvider } from "./context/LanguageContext";

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-inter',
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} >
      <head>
         <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <StoreProvider>
        <body
        className="font-sans bg-background-light dark:bg-background-dark text-slate-900 dark:text-white transition-colors duration-300"
        >
          <LanguageProvider>
            {children}
          </LanguageProvider>
        </body>
      </StoreProvider>
    </html>
  );
}
