-- This script was generated by the ERD tool in pgAdmin 4 and manually corrected
BEGIN;

CREATE TYPE role_types AS ENUM (
    'GUEST',
    'OWNER',
    'ROOT'
);

CREATE TYPE movement_types AS ENUM (
    'IN',
    'OUT',
    'DAMAGED',
    'EXPIRED',
    'RETURNED_IN',
    'RETURNED_OUT'
    'ADJUSTMENT'
);

CREATE TYPE sales_types AS ENUM (
    'PRENDING',
    'CANCELLED',
    'COMPLETED'
);



CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password_hash character varying(100) NOT NULL,
    role role_types NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.user_refresh_token
(
    id uuid NOT NULL,
    token character varying(200) NOT NULL,
    expired_at timestamp with time zone NOT NULL DEFAULT now(),
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.units
(
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    symbol character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id uuid NOT NULL,
    name character varying NOT NULL,
    barcode character varying,
    updated_at timestamp with time zone DEFAULT now(),
    minimum_stock integer CHECK (minimum_stock >= 0),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    unit_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.recipe
(
    id uuid NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(400),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.recipe_products
(
    id uuid NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    recipe_id uuid NOT NULL,
    product_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sellable_item
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
	is_active boolean NOT NULL DEFAULT TRUE,
    product_id uuid,
    recipe_id uuid,
    PRIMARY KEY (id),
    CONSTRAINT sellable_item_type_check CHECK (
        (product_id IS NOT NULL AND recipe_id IS NULL)
     OR (product_id IS NULL AND recipe_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS public.sales_price
(
    id uuid NOT NULL,
    price numeric(10, 2) NOT NULL CHECK (price >= 0),
    start_date timestamp with time zone NOT NULL DEFAULT now(),
    end_date timestamp with time zone,
    sellable_item_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sales
(
    id uuid NOT NULL,
    status sales_types NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    total_amount numeric(10, 2) NOT NULL CHECK (total_amount >= 0),
    user_id uuid,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sales_item
(
    id uuid NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(10, 2) NOT NULL CHECK (unit_price >= 0),
    total_price numeric(10, 2) NOT NULL CHECK (total_price >= 0),
    sellable_item_id uuid NOT NULL,
    sale_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.batch
(
    id uuid NOT NULL,
    quantity integer NOT NULL CHECK (quantity >= 0),
    initial_quantity integer NOT NULL CHECK (initial_quantity > 0),
    expiration_date date NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    is_active boolean NOT NULL,
    reference character varying(200),
    product_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cost_price
(
    id uuid NOT NULL,
    price numeric(10, 2) NOT NULL CHECK (price >= 0),
    start_date timestamp with time zone NOT NULL DEFAULT now(),
    end_date timestamp with time zone,
    batch_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stock_movement
(
    id uuid NOT NULL,
    quantity integer NOT NULL CHECK (quantity <> 0),
    movement_type movement_types NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    batch_id uuid NOT NULL,
    user_id uuid NOT NULL,
    PRIMARY KEY (id)
);

-- Foreign Keys

ALTER TABLE public.user_refresh_token
    ADD CONSTRAINT user_refresh_token_user_fk
    FOREIGN KEY (user_id) REFERENCES public.users (id);

ALTER TABLE public.products
    ADD CONSTRAINT products_unit_fk
    FOREIGN KEY (unit_id) REFERENCES public.units (id);

ALTER TABLE public.recipe_products
    ADD CONSTRAINT recipe_products_recipe_fk
    FOREIGN KEY (recipe_id) REFERENCES public.recipe (id);

ALTER TABLE public.recipe_products
    ADD CONSTRAINT recipe_products_product_fk
    FOREIGN KEY (product_id) REFERENCES public.products (id);

ALTER TABLE public.sellable_item
    ADD CONSTRAINT sellable_item_product_fk
    FOREIGN KEY (product_id) REFERENCES public.products (id);

ALTER TABLE public.sellable_item
    ADD CONSTRAINT sellable_item_recipe_fk
    FOREIGN KEY (recipe_id) REFERENCES public.recipe (id);

ALTER TABLE public.sales_price
    ADD CONSTRAINT sales_price_sellable_item_fk
    FOREIGN KEY (sellable_item_id) REFERENCES public.sellable_item (id);

ALTER TABLE public.sales
    ADD CONSTRAINT sales_user_fk
    FOREIGN KEY (user_id) REFERENCES public.users (id);

ALTER TABLE public.sales_item
    ADD CONSTRAINT sales_item_sale_fk
    FOREIGN KEY (sale_id) REFERENCES public.sales (id);

ALTER TABLE public.sales_item
    ADD CONSTRAINT sales_item_sellable_item_fk
    FOREIGN KEY (sellable_item_id) REFERENCES public.sellable_item (id);

ALTER TABLE public.batch
    ADD CONSTRAINT batch_product_fk
    FOREIGN KEY (product_id) REFERENCES public.products (id);

ALTER TABLE public.cost_price
    ADD CONSTRAINT cost_price_batch_fk
    FOREIGN KEY (batch_id) REFERENCES public.batch (id);

ALTER TABLE public.stock_movement
    ADD CONSTRAINT stock_movement_batch_fk
    FOREIGN KEY (batch_id) REFERENCES public.batch (id);

ALTER TABLE public.stock_movement
    ADD CONSTRAINT stock_movement_user_fk
    FOREIGN KEY (user_id) REFERENCES public.users (id);
	
CREATE INDEX idx_sales_created_at ON sales(created_at);
CREATE INDEX idx_stock_movement_created_at ON stock_movement(created_at);
CREATE INDEX idx_sales_item_sale_id ON sales_item(sale_id);

COMMIT;